// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: mp2/proto/hydfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Filename        string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data            []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FileContentHash string                 `protobuf:"bytes,3,opt,name=file_content_hash,json=fileContentHash,proto3" json:"file_content_hash,omitempty"`
	FileNameHash    int32                  `protobuf:"varint,4,opt,name=file_name_hash,json=fileNameHash,proto3" json:"file_name_hash,omitempty"`
	CreationTime    string                 `protobuf:"bytes,5,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_mp2_proto_hydfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mp2_proto_hydfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_mp2_proto_hydfs_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetFileContentHash() string {
	if x != nil {
		return x.FileContentHash
	}
	return ""
}

func (x *FileChunk) GetFileNameHash() int32 {
	if x != nil {
		return x.FileNameHash
	}
	return 0
}

func (x *FileChunk) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_mp2_proto_hydfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mp2_proto_hydfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_mp2_proto_hydfs_proto_rawDescGZIP(), []int{1}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_mp2_proto_hydfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mp2_proto_hydfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_mp2_proto_hydfs_proto_rawDescGZIP(), []int{2}
}

func (x *UploadStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AppendChunk struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data              []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	AppendContentHash string                 `protobuf:"bytes,3,opt,name=append_content_hash,json=appendContentHash,proto3" json:"append_content_hash,omitempty"`
	AppendId          string                 `protobuf:"bytes,4,opt,name=append_id,json=appendId,proto3" json:"append_id,omitempty"`
	ClientId          string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientTimestamp   string                 `protobuf:"bytes,6,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendChunk) Reset() {
	*x = AppendChunk{}
	mi := &file_mp2_proto_hydfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendChunk) ProtoMessage() {}

func (x *AppendChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mp2_proto_hydfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendChunk.ProtoReflect.Descriptor instead.
func (*AppendChunk) Descriptor() ([]byte, []int) {
	return file_mp2_proto_hydfs_proto_rawDescGZIP(), []int{3}
}

func (x *AppendChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AppendChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppendChunk) GetAppendContentHash() string {
	if x != nil {
		return x.AppendContentHash
	}
	return ""
}

func (x *AppendChunk) GetAppendId() string {
	if x != nil {
		return x.AppendId
	}
	return ""
}

func (x *AppendChunk) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AppendChunk) GetClientTimestamp() string {
	if x != nil {
		return x.ClientTimestamp
	}
	return ""
}

var File_mp2_proto_hydfs_proto protoreflect.FileDescriptor

const file_mp2_proto_hydfs_proto_rawDesc = "" +
	"\n" +
	"\x15mp2/proto/hydfs.proto\x12\x05proto\"\xb2\x01\n" +
	"\tFileChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12*\n" +
	"\x11file_content_hash\x18\x03 \x01(\tR\x0ffileContentHash\x12$\n" +
	"\x0efile_name_hash\x18\x04 \x01(\x05R\ffileNameHash\x12#\n" +
	"\rcreation_time\x18\x05 \x01(\tR\fcreationTime\")\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"B\n" +
	"\fUploadStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd2\x01\n" +
	"\vAppendChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12.\n" +
	"\x13append_content_hash\x18\x03 \x01(\tR\x11appendContentHash\x12\x1b\n" +
	"\tappend_id\x18\x04 \x01(\tR\bappendId\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12)\n" +
	"\x10client_timestamp\x18\x06 \x01(\tR\x0fclientTimestamp2\xb7\x01\n" +
	"\fHyDFSService\x127\n" +
	"\fFileTransfer\x12\x10.proto.FileChunk\x1a\x13.proto.UploadStatus(\x01\x121\n" +
	"\aGetFile\x12\x12.proto.FileRequest\x1a\x10.proto.FileChunk0\x01\x12;\n" +
	"\x0eAppendTransfer\x12\x12.proto.AppendChunk\x1a\x13.proto.UploadStatus(\x01B'Z%distributed_log_query/mp2/proto;protob\x06proto3"

var (
	file_mp2_proto_hydfs_proto_rawDescOnce sync.Once
	file_mp2_proto_hydfs_proto_rawDescData []byte
)

func file_mp2_proto_hydfs_proto_rawDescGZIP() []byte {
	file_mp2_proto_hydfs_proto_rawDescOnce.Do(func() {
		file_mp2_proto_hydfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mp2_proto_hydfs_proto_rawDesc), len(file_mp2_proto_hydfs_proto_rawDesc)))
	})
	return file_mp2_proto_hydfs_proto_rawDescData
}

var file_mp2_proto_hydfs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mp2_proto_hydfs_proto_goTypes = []any{
	(*FileChunk)(nil),    // 0: proto.FileChunk
	(*FileRequest)(nil),  // 1: proto.FileRequest
	(*UploadStatus)(nil), // 2: proto.UploadStatus
	(*AppendChunk)(nil),  // 3: proto.AppendChunk
}
var file_mp2_proto_hydfs_proto_depIdxs = []int32{
	0, // 0: proto.HyDFSService.FileTransfer:input_type -> proto.FileChunk
	1, // 1: proto.HyDFSService.GetFile:input_type -> proto.FileRequest
	3, // 2: proto.HyDFSService.AppendTransfer:input_type -> proto.AppendChunk
	2, // 3: proto.HyDFSService.FileTransfer:output_type -> proto.UploadStatus
	0, // 4: proto.HyDFSService.GetFile:output_type -> proto.FileChunk
	2, // 5: proto.HyDFSService.AppendTransfer:output_type -> proto.UploadStatus
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mp2_proto_hydfs_proto_init() }
func file_mp2_proto_hydfs_proto_init() {
	if File_mp2_proto_hydfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mp2_proto_hydfs_proto_rawDesc), len(file_mp2_proto_hydfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mp2_proto_hydfs_proto_goTypes,
		DependencyIndexes: file_mp2_proto_hydfs_proto_depIdxs,
		MessageInfos:      file_mp2_proto_hydfs_proto_msgTypes,
	}.Build()
	File_mp2_proto_hydfs_proto = out.File
	file_mp2_proto_hydfs_proto_goTypes = nil
	file_mp2_proto_hydfs_proto_depIdxs = nil
}
