// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: mp2/proto/hydfs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HyDFSService_FileTransfer_FullMethodName   = "/proto.HyDFSService/FileTransfer"
	HyDFSService_GetFile_FullMethodName        = "/proto.HyDFSService/GetFile"
	HyDFSService_AppendTransfer_FullMethodName = "/proto.HyDFSService/AppendTransfer"
)

// HyDFSServiceClient is the client API for HyDFSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyDFSServiceClient interface {
	// Client streams file chunks to the server
	FileTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadStatus], error)
	// Server streams file chunks back to the client
	GetFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// Append transfer stream
	AppendTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendChunk, UploadStatus], error)
}

type hyDFSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHyDFSServiceClient(cc grpc.ClientConnInterface) HyDFSServiceClient {
	return &hyDFSServiceClient{cc}
}

func (c *hyDFSServiceClient) FileTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyDFSService_ServiceDesc.Streams[0], HyDFSService_FileTransfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_FileTransferClient = grpc.ClientStreamingClient[FileChunk, UploadStatus]

func (c *hyDFSServiceClient) GetFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyDFSService_ServiceDesc.Streams[1], HyDFSService_GetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_GetFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *hyDFSServiceClient) AppendTransfer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendChunk, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyDFSService_ServiceDesc.Streams[2], HyDFSService_AppendTransfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendChunk, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_AppendTransferClient = grpc.ClientStreamingClient[AppendChunk, UploadStatus]

// HyDFSServiceServer is the server API for HyDFSService service.
// All implementations must embed UnimplementedHyDFSServiceServer
// for forward compatibility.
type HyDFSServiceServer interface {
	// Client streams file chunks to the server
	FileTransfer(grpc.ClientStreamingServer[FileChunk, UploadStatus]) error
	// Server streams file chunks back to the client
	GetFile(*FileRequest, grpc.ServerStreamingServer[FileChunk]) error
	// Append transfer stream
	AppendTransfer(grpc.ClientStreamingServer[AppendChunk, UploadStatus]) error
	mustEmbedUnimplementedHyDFSServiceServer()
}

// UnimplementedHyDFSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHyDFSServiceServer struct{}

func (UnimplementedHyDFSServiceServer) FileTransfer(grpc.ClientStreamingServer[FileChunk, UploadStatus]) error {
	return status.Errorf(codes.Unimplemented, "method FileTransfer not implemented")
}
func (UnimplementedHyDFSServiceServer) GetFile(*FileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedHyDFSServiceServer) AppendTransfer(grpc.ClientStreamingServer[AppendChunk, UploadStatus]) error {
	return status.Errorf(codes.Unimplemented, "method AppendTransfer not implemented")
}
func (UnimplementedHyDFSServiceServer) mustEmbedUnimplementedHyDFSServiceServer() {}
func (UnimplementedHyDFSServiceServer) testEmbeddedByValue()                      {}

// UnsafeHyDFSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyDFSServiceServer will
// result in compilation errors.
type UnsafeHyDFSServiceServer interface {
	mustEmbedUnimplementedHyDFSServiceServer()
}

func RegisterHyDFSServiceServer(s grpc.ServiceRegistrar, srv HyDFSServiceServer) {
	// If the following call pancis, it indicates UnimplementedHyDFSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HyDFSService_ServiceDesc, srv)
}

func _HyDFSService_FileTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HyDFSServiceServer).FileTransfer(&grpc.GenericServerStream[FileChunk, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_FileTransferServer = grpc.ClientStreamingServer[FileChunk, UploadStatus]

func _HyDFSService_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HyDFSServiceServer).GetFile(m, &grpc.GenericServerStream[FileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_GetFileServer = grpc.ServerStreamingServer[FileChunk]

func _HyDFSService_AppendTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HyDFSServiceServer).AppendTransfer(&grpc.GenericServerStream[AppendChunk, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_AppendTransferServer = grpc.ClientStreamingServer[AppendChunk, UploadStatus]

// HyDFSService_ServiceDesc is the grpc.ServiceDesc for HyDFSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HyDFSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HyDFSService",
	HandlerType: (*HyDFSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileTransfer",
			Handler:       _HyDFSService_FileTransfer_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _HyDFSService_GetFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AppendTransfer",
			Handler:       _HyDFSService_AppendTransfer_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mp2/proto/hydfs.proto",
}
