// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/hydfs.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HyDFSService_UploadFile_FullMethodName = "/hydfs.HyDFSService/UploadFile"
)

// HyDFSServiceClient is the client API for HyDFSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyDFSServiceClient interface {
	// Client streams file chunks to the server
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadStatus], error)
}

type hyDFSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHyDFSServiceClient(cc grpc.ClientConnInterface) HyDFSServiceClient {
	return &hyDFSServiceClient{cc}
}

func (c *hyDFSServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyDFSService_ServiceDesc.Streams[0], HyDFSService_UploadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_UploadFileClient = grpc.ClientStreamingClient[FileChunk, UploadStatus]

// HyDFSServiceServer is the server API for HyDFSService service.
// All implementations must embed UnimplementedHyDFSServiceServer
// for forward compatibility.
type HyDFSServiceServer interface {
	// Client streams file chunks to the server
	UploadFile(grpc.ClientStreamingServer[FileChunk, UploadStatus]) error
	mustEmbedUnimplementedHyDFSServiceServer()
}

// UnimplementedHyDFSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHyDFSServiceServer struct{}

func (UnimplementedHyDFSServiceServer) UploadFile(grpc.ClientStreamingServer[FileChunk, UploadStatus]) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedHyDFSServiceServer) mustEmbedUnimplementedHyDFSServiceServer() {}
func (UnimplementedHyDFSServiceServer) testEmbeddedByValue()                      {}

// UnsafeHyDFSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyDFSServiceServer will
// result in compilation errors.
type UnsafeHyDFSServiceServer interface {
	mustEmbedUnimplementedHyDFSServiceServer()
}

func RegisterHyDFSServiceServer(s grpc.ServiceRegistrar, srv HyDFSServiceServer) {
	// If the following call pancis, it indicates UnimplementedHyDFSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HyDFSService_ServiceDesc, srv)
}

func _HyDFSService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HyDFSServiceServer).UploadFile(&grpc.GenericServerStream[FileChunk, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyDFSService_UploadFileServer = grpc.ClientStreamingServer[FileChunk, UploadStatus]

// HyDFSService_ServiceDesc is the grpc.ServiceDesc for HyDFSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HyDFSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hydfs.HyDFSService",
	HandlerType: (*HyDFSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _HyDFSService_UploadFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hydfs.proto",
}
